[package]
name = "notty-smart-contract"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "notty_smart_contract"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
init-if-needed = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "=0.31.0", features = ["init-if-needed"] }
anchor-spl = { version = "=0.31.0", features = ["metadata"] }
raydium-launch-cpi = { git = "https://github.com/raydium-io/raydium-cpi", package = "raydium-launch-cpi", branch = "anchor-0.31.0" }
